from django.conf.urls import patterns, url
from ece import views
from ece.models import News,createGroup,courses,facultymem
urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^research/$', views.rMenu, name='rMenu'),
    url(r'^courses/$', views.rcourses, name='rCourses'),
    url(r'^faculty/$', views.rfaculty, name='rFaculty'),
    url(r'^lab/$', views.rLab, name='rLab'),
    url(r'^publication/$', views.rpublication, name='rPublication'),
    url(r'^research/news/$', views.rNews, name='rNews'),
    url(r'^research/events/$', views.rComingEvent, name='rComingEvent'),
    #url(r'^research/news/(?P<heading>[-\w]+)/$', views.news_detail),
    url(r'^research/(?P<title>[-\w]+)/$', views.createGroup_detail),
    url(r'^lab/(?P<lab_code>[-\w]+)/$', views.lab_detail),
    url(r'^lab/(?P<lab_code>[-\w]+)/members$', views.labMem_detail),
    url(r'^lab/(?P<lab_code>[-\w]+)/research$', views.labRes_detail),
    url(r'^lab/(?P<lab_code>[-\w]+)/publications$', views.labPub_detail),
    url(r'^faculty/(?P<facultycode>[-\w]+)/$', views.faculty_detail),
    url(r'^courses/(?P<coursecode>[-\w]+)/$', views.course_detail),
    url(r'^publication/(?P<pubDetail>[-\w]+)/$', views.publication_detail),
    url(r'^research/news/(?P<news_id_id>\d+)/$', views.news_detail, name='news_detail'),
    url(r'^research/events/(?P<comingevent_id_id>\d+)/$', views.ComingEvent_detail, name='comingEvent_detail'),
    #url(r'^research/SIP/$', views.rGroup1, name='rGroup1'),
    #url(r'^research/CE/$', views.rGroup2, name='rGroup2'),
    #url(r'^research/CES/$', views.rGroup3, name='rGroup3'),
    #url(r'^research/VLSI/$', views.rGroup4, name='rGroup4'),
    #url(r'^news/(?P<news_id_id>\d+)/$', views.news_detail, name='news_detail'),
    #url(r'^news/$', views.allnews, name='allnews'),
    #url(r'^research/news/'+str(News.objects.get(pk=1))+'/$', views.news_detail, name='news_detail'),
)
